MyProjects/Ruby/Rails/Demo001-demo/config/routes.rb
Rails.application.routes.draw do
  get 'say/hello'

  get 'say/goodbye'

end

MyProjects/Ruby/Rails/Demo001-demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

MyProjects/Ruby/Rails/Demo001-demo/app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
	  @time=Time.now
  end

  def goodbye
  end
end

MyProjects/Ruby/Rails/Demo001-demo/app/helpers/application_helper.rb
module ApplicationHelper
end

MyProjects/Ruby/Rails/Demo001-demo/app/helpers/say_helper.rb
module SayHelper
end

MyProjects/Ruby/Rails/Demo001-demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo001Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

MyProjects/Ruby/Rails/Demo001-demo/app/views/say/goodbye.html.erb
<h1>Say#goodbye</h1>
<p>Say <a href="/say/hello">Hello</a></p>
<p>Time to say <%= link_to "Hello" , say_hello_path %>!</p>

MyProjects/Ruby/Rails/Demo001-demo/app/views/say/hello.html.erb
<p>Hello world</p>
<p>It is <%= Time.now%> now</p>
<p>It is Time : <%= @time %> </p>
<p>
	say <a href="/say/goodbye">goodBye</a>
</p>
<p>
	Time to say <%= link_to "GoodBye" , say_goodbye_path %>!
</p>